### PR TITLE
add: rocky ridge grid

### PR DESCRIPTION
**Pull request by eneemann**
Adding Rocky Ridge grid in northern Juab county, taking a chunk out of Mona's grid.

### CODE REVIEW

**Comment by eneemann** [comment]
Did I do this right?

**Comment by steveoh** [comment]
So far it looks good.

**Comment by steveoh** [comment]
@eneemann ballpark... when will this data be available in the sgid for forklift?

**Comment by steveoh** [comment]
Also, higher numbers get priority. Is that correct for mona vs rocky ridge?

**Comment by eneemann** [comment]
> @eneemann ballpark... when will this data be available in the sgid for forklift?

I already loaded it there

**Review by steveoh — APPROVED** [review]

**Pull request merged**
