### PR TITLE
GKE deployment files

### PR DESCRIPTION
**Pull request by keatonwalker**
Created new deployment files for GKE. The files are based on the development deployments with changes for Kube in GKE added.

### CODE REVIEW

**Comment by steveoh** [comment]
What parts are missing from this to be merged?

**Comment by steveoh** [comment]
Why is this still WIP?

**Comment by keatonwalker** [comment]
Mostly because I thought I needed to figure out a different solution for the IP of the ArcGIS machine, but I discovered how to assign it on creation in GCP.

The last thing is the DB environment variables being hard coded. We need to change this before it leaves development, but we could merge it into the development branch for now if it helps?

**Comment by steveoh** [comment]
Remind me about the db hardcoded env variables...

**Comment by keatonwalker** [comment]
All the web-api env variable values are hardcoded now. The values should eventually come from a ConfigMap or Secrets object.

The main one I am thinking about is WEBAPI__DATABASE__PASSWORD. In our development the DB is isolated in the cluster and we destroy the cluster when we are done, so access is limited.

**Comment by steveoh** [comment]
Right. Those are things that will be stored outside of this repo correct? The items in here should only be for getting the basic system running. Let's chat about this so we can get on the same page.

**Pull request merged**
